"""tables

Revision ID: 8c7913e642c4
Revises: 001_create_core_tables
Create Date: 2026-03-19 10:13:28.391001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7913e642c4'
down_revision: Union[str, None] = '001_create_core_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower_entities',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('constitution', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_entities_name'), 'borrower_entities', ['name'], unique=False)
    op.create_table('credential_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('auth_type', sa.String(length=64), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('webhook_path', sa.String(length=255), nullable=True),
    sa.Column('cron_expression', sa.String(length=255), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('graph_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_applications',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('borrower_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('facility_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('recommended_limit', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('dscr_ratio', sa.Float(), nullable=True),
    sa.Column('leverage_ratio', sa.Float(), nullable=True),
    sa.Column('gstr_mismatch_flag', sa.Boolean(), nullable=True),
    sa.Column('nclt_flag', sa.Boolean(), nullable=True),
    sa.Column('pd_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_applications_borrower_id'), 'credit_applications', ['borrower_id'], unique=False)
    op.create_table('execution_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('initiated_by', sa.String(length=255), nullable=True),
    sa.Column('initial_payload_json', sa.JSON(), nullable=False),
    sa.Column('final_payload_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_runs_workflow_id'), 'execution_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_edge_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('edge_id', sa.String(length=128), nullable=False),
    sa.Column('source_node_id', sa.String(length=128), nullable=False),
    sa.Column('target_node_id', sa.String(length=128), nullable=False),
    sa.Column('source_handle', sa.String(length=64), nullable=True),
    sa.Column('target_handle', sa.String(length=64), nullable=True),
    sa.Column('edge_type', sa.String(length=64), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_edge_definitions_edge_id'), 'workflow_edge_definitions', ['edge_id'], unique=False)
    op.create_index(op.f('ix_workflow_edge_definitions_source_node_id'), 'workflow_edge_definitions', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_workflow_edge_definitions_target_node_id'), 'workflow_edge_definitions', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_workflow_edge_definitions_workflow_id'), 'workflow_edge_definitions', ['workflow_id'], unique=False)
    op.create_table('workflow_node_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('execution_config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_node_definitions_node_id'), 'workflow_node_definitions', ['node_id'], unique=False)
    op.create_index(op.f('ix_workflow_node_definitions_workflow_id'), 'workflow_node_definitions', ['workflow_id'], unique=False)
    op.create_table('credit_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('character_score', sa.Float(), nullable=True),
    sa.Column('capacity_score', sa.Float(), nullable=True),
    sa.Column('capital_score', sa.Float(), nullable=True),
    sa.Column('collateral_score', sa.Float(), nullable=True),
    sa.Column('conditions_score', sa.Float(), nullable=True),
    sa.Column('character_summary', sa.Text(), nullable=True),
    sa.Column('capacity_summary', sa.Text(), nullable=True),
    sa.Column('capital_summary', sa.Text(), nullable=True),
    sa.Column('collateral_summary', sa.Text(), nullable=True),
    sa.Column('conditions_summary', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('debt_service_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('full_text_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['credit_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_records_application_id'), 'credit_records', ['application_id'], unique=False)
    op.create_index(op.f('ix_credit_records_company_name'), 'credit_records', ['company_name'], unique=False)
    op.create_table('dead_letter_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('failure_stage', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_executions_execution_id'), 'dead_letter_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_dead_letter_executions_workflow_id'), 'dead_letter_executions', ['workflow_id'], unique=False)
    op.create_table('immutable_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('exact_timestamp', sa.DateTime(), nullable=False),
    sa.Column('input_payload_json', sa.JSON(), nullable=False),
    sa.Column('ruleset_json', sa.JSON(), nullable=False),
    sa.Column('deterministic_outcome_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['credit_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immutable_audit_logs_application_id'), 'immutable_audit_logs', ['application_id'], unique=True)
    op.create_table('node_execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_payload_json', sa.JSON(), nullable=True),
    sa.Column('output_payload_json', sa.JSON(), nullable=True),
    sa.Column('source_edges_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_execution_logs_execution_id'), 'node_execution_logs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_node_execution_logs_node_id'), 'node_execution_logs', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_execution_logs_workflow_id'), 'node_execution_logs', ['workflow_id'], unique=False)
    op.alter_column('approval_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_node_execution_logs_workflow_id'), table_name='node_execution_logs')
    op.drop_index(op.f('ix_node_execution_logs_node_id'), table_name='node_execution_logs')
    op.drop_index(op.f('ix_node_execution_logs_execution_id'), table_name='node_execution_logs')
    op.drop_table('node_execution_logs')
    op.drop_index(op.f('ix_immutable_audit_logs_application_id'), table_name='immutable_audit_logs')
    op.drop_table('immutable_audit_logs')
    op.drop_index(op.f('ix_dead_letter_executions_workflow_id'), table_name='dead_letter_executions')
    op.drop_index(op.f('ix_dead_letter_executions_execution_id'), table_name='dead_letter_executions')
    op.drop_table('dead_letter_executions')
    op.drop_index(op.f('ix_credit_records_company_name'), table_name='credit_records')
    op.drop_index(op.f('ix_credit_records_application_id'), table_name='credit_records')
    op.drop_table('credit_records')
    op.drop_index(op.f('ix_workflow_node_definitions_workflow_id'), table_name='workflow_node_definitions')
    op.drop_index(op.f('ix_workflow_node_definitions_node_id'), table_name='workflow_node_definitions')
    op.drop_table('workflow_node_definitions')
    op.drop_index(op.f('ix_workflow_edge_definitions_workflow_id'), table_name='workflow_edge_definitions')
    op.drop_index(op.f('ix_workflow_edge_definitions_target_node_id'), table_name='workflow_edge_definitions')
    op.drop_index(op.f('ix_workflow_edge_definitions_source_node_id'), table_name='workflow_edge_definitions')
    op.drop_index(op.f('ix_workflow_edge_definitions_edge_id'), table_name='workflow_edge_definitions')
    op.drop_table('workflow_edge_definitions')
    op.drop_index(op.f('ix_execution_runs_workflow_id'), table_name='execution_runs')
    op.drop_table('execution_runs')
    op.drop_index(op.f('ix_credit_applications_borrower_id'), table_name='credit_applications')
    op.drop_table('credit_applications')
    op.drop_table('workflow_definitions')
    op.drop_table('credential_records')
    op.drop_index(op.f('ix_borrower_entities_name'), table_name='borrower_entities')
    op.drop_table('borrower_entities')
    # ### end Alembic commands ###
